//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistent
    {
        public Asistent()
        {
            this.Tema = new HashSet<Tema>();
            this.Test = new HashSet<Test>();
        }
    
        public int id { get; set; }
        public string nume { get; set; }
        public string prenume { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
        public virtual ICollection<Tema> Tema { get; set; }
        public virtual ICollection<Test> Test { get; set; }

        public Asistent(int id, string nume, string prenume)
        {
            this.id = id;
            this.nume = nume;
            this.prenume = prenume;
        }
    }
}
