//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curs
    {
        public Curs()
        {
            this.Inscriere = new HashSet<Inscriere>();
            this.Nota = new HashSet<Nota>();
            this.Test = new HashSet<Test>();
        }
    
        public int id { get; set; }
        public string nume { get; set; }
        public Nullable<int> numarCredite { get; set; }
        public Nullable<int> idProfesor { get; set; }
    
        public virtual Profesor Profesor { get; set; }
        public virtual ICollection<Inscriere> Inscriere { get; set; }
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual ICollection<Test> Test { get; set; }
    }
}
