//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenumireCursuri
    {
        public int id { get; set; }
        public Nullable<int> idCurs { get; set; }
        public string denumire { get; set; }
    
        public virtual Curs Curs { get; set; }
    }
}
