//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscriere
    {
        public int idStudent { get; set; }
        public int idCurs { get; set; }
        public string numeStudent { get; set; }
        public string prenumeStudent { get; set; }
        public string email { get; set; }
        public string parola { get; set; }
    
        public virtual Curs Curs { get; set; }
        public virtual Student Student { get; set; }
    }
}
