//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspuns
    {
        public int id { get; set; }
        public Nullable<int> idIntrebare { get; set; }
        public string mesaj { get; set; }
        public string utilizator { get; set; }
        public Nullable<System.DateTime> dataRaspuns { get; set; }
    
        public virtual Intrebare Intrebare { get; set; }
    }
}
