//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Inscriere = new HashSet<Inscriere>();
            this.Nota = new HashSet<Nota>();
            this.Tema = new HashSet<Tema>();
            this.Test = new HashSet<Test>();
        }
    
        public int id { get; set; }
        public string nume { get; set; }
        public string prenume { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Inscriere> Inscriere { get; set; }
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Utilizator Utilizator { get; set; }
        public virtual ICollection<Tema> Tema { get; set; }
        public virtual ICollection<Test> Test { get; set; }
    }
}
